version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "spring_course"
      MYSQL_DATABASE: "spring_course"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
